# Generated by Django 4.0.3 on 2022-11-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lh', models.CharField(default='', max_length=20, unique=True, verbose_name='楼号')),
                ('fh', models.CharField(default='', max_length=20, unique=True, verbose_name='房号')),
                ('jzmj', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='建筑面积')),
            ],
            options={
                'verbose_name': '楼房',
                'verbose_name_plural': '楼房',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='操作员')),
                ('pwd', models.CharField(default='', max_length=100, verbose_name='登录密码')),
                ('photo', models.ImageField(upload_to='app01/', verbose_name='头像')),
                ('tele', models.CharField(default='', max_length=20, verbose_name='手机')),
            ],
            options={
                'verbose_name': '操作用户表',
                'verbose_name_plural': '操作用户表',
            },
        ),
        migrations.CreateModel(
            name='Yz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=50)),
                ('carid', models.CharField(default='', max_length=20, verbose_name='证件号码')),
                ('gzdw', models.CharField(default='', max_length=100, verbose_name='工作单位')),
            ],
            options={
                'verbose_name': '业主信息表',
                'verbose_name_plural': '业主信息表',
            },
        ),
        migrations.CreateModel(
            name='WyfBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sj', models.DateTimeField(default='', verbose_name='日期')),
                ('billno', models.CharField(default='', max_length=20, verbose_name='账单编号')),
                ('zy', models.CharField(default='', max_length=80, verbose_name='摘要')),
                ('yingjiaomoney', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='应交数额')),
                ('yijiaomoney', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已交数额')),
                ('lj', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.lf', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '物业费账单表',
                'verbose_name_plural': '物业费账单表',
            },
        ),
        migrations.AddField(
            model_name='lf',
            name='yz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.yz', verbose_name='业主'),
        ),
    ]
