# Generated by Django 4.0.3 on 2022-11-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_yz_tele'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yz',
            old_name='carid',
            new_name='cardid',
        ),
    ]
