# Generated by Django 4.0.3 on 2022-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=100, unique=True, verbose_name='用户名')),
                ('account', models.CharField(db_index=True, default='', max_length=20, unique=True, verbose_name='账号')),
                ('tele', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('pwd', models.CharField(default='', max_length=100, verbose_name='密码')),
                ('photo', models.CharField(default='', max_length=100, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
