# Generated by Django 4.0.3 on 2022-12-17 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 5, 45, 3, 766063, tzinfo=utc), verbose_name='注册日期'),
            preserve_default=False,
        ),
    ]
