# Generated by Django 4.0.3 on 2022-12-22 17:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0002_users_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kmb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_parentId', models.IntegerField(default=None, null=True, verbose_name='父级编码')),
                ('kmbm', models.CharField(db_index=True, default='', max_length=12, unique=True, verbose_name='科目编码')),
                ('kmmc', models.CharField(db_index=True, default='', max_length=80, verbose_name='科目名称')),
                ('kmxz', models.IntegerField(choices=[(1, '借方'), (2, '贷方')], default=1)),
                ('zbqy', models.BooleanField(default=False, verbose_name='账簿启用')),
            ],
            options={
                'verbose_name': '科目表',
                'verbose_name_plural': '科目表',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册日期'),
        ),
        migrations.CreateModel(
            name='Mxz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ywxh', models.CharField(default='', max_length=12, unique=True, verbose_name='业务编号')),
                ('rq', models.DateField(default=datetime.date(2022, 12, 22), verbose_name='业务日期')),
                ('jfsl', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='借方数量')),
                ('jfje', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='借方金额')),
                ('dfsl', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='贷方数量')),
                ('dfje', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='贷方金额')),
                ('ywzt', models.IntegerField(choices=[(0, '未复核'), (1, '已复核'), (2, '已记账')], verbose_name='业务状态')),
                ('srr', models.CharField(default='', max_length=20, verbose_name='业务输入')),
                ('shr', models.CharField(default='', max_length=20, verbose_name='业务输入')),
                ('jzr', models.CharField(default='', max_length=20, verbose_name='业务输入')),
                ('kmbm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jxc.kmb')),
            ],
        ),
        migrations.CreateModel(
            name='Kmye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qcsl', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='期初数量')),
                ('qcje', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='期初金额')),
                ('jfsl', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='借方数量')),
                ('jfje', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='借方金额')),
                ('dfsl', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='贷方数量')),
                ('dfje', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='贷方金额')),
                ('qmsl', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='期末数量')),
                ('qmje', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='期末金额')),
                ('kmbm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jxc.kmb')),
            ],
            options={
                'verbose_name': '科目余额表',
                'verbose_name_plural': '科目余额表',
            },
        ),
    ]
