# Generated by Django 4.0.3 on 2022-12-22 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0003_kmb_alter_users_createtime_mxz_kmye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mxz',
            name='rq',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 17, 15, 51, 783622), verbose_name='业务日期'),
        ),
    ]
