# Generated by Django 4.0.3 on 2022-12-22 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0004_alter_mxz_rq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mxz',
            name='rq',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='业务日期'),
        ),
    ]
