# Generated by Django 4.0.3 on 2022-12-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0005_alter_mxz_rq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mxz',
            options={'verbose_name': '业务明细表', 'verbose_name_plural': '业务明细表'},
        ),
        migrations.RenameField(
            model_name='kmye',
            old_name='kmbm',
            new_name='kmb',
        ),
        migrations.RenameField(
            model_name='mxz',
            old_name='kmbm',
            new_name='kmb',
        ),
        migrations.AlterField(
            model_name='mxz',
            name='jzr',
            field=models.CharField(default='', max_length=20, verbose_name='记账'),
        ),
        migrations.AlterField(
            model_name='mxz',
            name='shr',
            field=models.CharField(default='', max_length=20, verbose_name='审核'),
        ),
        migrations.AlterField(
            model_name='mxz',
            name='srr',
            field=models.CharField(default='', max_length=20, verbose_name='输入'),
        ),
    ]
