# Generated by Django 4.0.3 on 2022-12-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0006_alter_mxz_options_rename_kmbm_kmye_kmb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmye',
            name='qmje',
        ),
        migrations.RemoveField(
            model_name='kmye',
            name='qmsl',
        ),
        migrations.AlterField(
            model_name='kmye',
            name='dfje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='贷方金额'),
        ),
        migrations.AlterField(
            model_name='kmye',
            name='dfsl',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='贷方数量'),
        ),
        migrations.AlterField(
            model_name='kmye',
            name='jfje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='借方金额'),
        ),
        migrations.AlterField(
            model_name='kmye',
            name='jfsl',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='借方数量'),
        ),
        migrations.AlterField(
            model_name='kmye',
            name='qcje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='期初金额'),
        ),
        migrations.AlterField(
            model_name='kmye',
            name='qcsl',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='期初数量'),
        ),
        migrations.AlterField(
            model_name='mxz',
            name='dfje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='贷方金额'),
        ),
        migrations.AlterField(
            model_name='mxz',
            name='dfsl',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='贷方数量'),
        ),
        migrations.AlterField(
            model_name='mxz',
            name='jfje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='借方金额'),
        ),
        migrations.AlterField(
            model_name='mxz',
            name='jfsl',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='借方数量'),
        ),
        migrations.AlterField(
            model_name='mxz',
            name='ywzt',
            field=models.IntegerField(choices=[(0, '未复核'), (1, '已复核'), (2, '已记账')], default=0, verbose_name='业务状态'),
        ),
    ]
