# Generated by Django 4.0.3 on 2022-12-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0008_alter_mxz_ywxh'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmye',
            name='qmje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='期末金额'),
        ),
        migrations.AddField(
            model_name='kmye',
            name='qmsl',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='期末数量'),
        ),
    ]
