# Generated by Django 4.0.3 on 2022-12-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0012_kmb_dfje_kmb_dfsl_kmb_jfje_kmb_jfsl_kmb_qcje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmb',
            name='dfljje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='贷方累计金额'),
        ),
        migrations.AddField(
            model_name='kmb',
            name='dfljsl',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='贷方累计数量'),
        ),
        migrations.AddField(
            model_name='kmb',
            name='jfljje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='借方累计金额'),
        ),
        migrations.AddField(
            model_name='kmb',
            name='jfljsl',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='借方累计数量'),
        ),
    ]
