# Generated by Django 4.0.3 on 2022-12-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0013_kmb_dfljje_kmb_dfljsl_kmb_jfljje_kmb_jfljsl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zzb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rq', models.CharField(default='', max_length=7, verbose_name='日期')),
                ('jfsl', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='借方发生数量')),
                ('jfje', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='借方发生金额')),
                ('dfsl', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='贷方方发生数量')),
                ('dfje', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='贷方发生金额')),
                ('kmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jxc.kmb')),
            ],
            options={
                'verbose_name': '总账表',
                'verbose_name_plural': '总账表',
            },
        ),
    ]
