# Generated by Django 4.0.3 on 2022-12-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jxc', '0014_zzb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmb',
            name='dfje',
        ),
        migrations.RemoveField(
            model_name='kmb',
            name='dfljje',
        ),
        migrations.RemoveField(
            model_name='kmb',
            name='dfljsl',
        ),
        migrations.RemoveField(
            model_name='kmb',
            name='dfsl',
        ),
        migrations.RemoveField(
            model_name='kmb',
            name='jfje',
        ),
        migrations.RemoveField(
            model_name='kmb',
            name='jfljje',
        ),
        migrations.RemoveField(
            model_name='kmb',
            name='jfljsl',
        ),
        migrations.RemoveField(
            model_name='kmb',
            name='jfsl',
        ),
        migrations.RemoveField(
            model_name='kmb',
            name='qmje',
        ),
        migrations.RemoveField(
            model_name='kmb',
            name='qmsl',
        ),
    ]
